name: r13n_hooks

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  arb_parser:
    path: packages/arb_parser
  mason: ^0.1.0-dev
  meta: ^1.8.0
  path: ^1.8.2
  pubspec_parse: ^1.2.0
  yaml: ^3.1.1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.21.1
  very_good_analysis: ^6.0.0
